server:
  port: 8080
spring:
  application:
    name: "alccard"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  spring:
    datasource:
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: "postgres"
      password: 12345
      driver-class-name: "org.postgresql.Driver"
    jpa:
      hibernate:
        ddl-auto: "update"
      properties:
        hibernate:
          dialect: "org.hibernate.dialect.PostgreSQLDialect"
          format_sql: true
      show-sql: true
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true